/**
* Deal
* # Introduction A web service that accepts request by APIs and returns 1+ bridge deals  # OpenAPI Specification This API is documented in **OpenAPI format**  # Cross-Origin Resource Sharing This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with  [W3C spec](https://www.w3.org/TR/cors/). And that allows cross-domain communication from the browser. All responses have a wildcard same-origin which makes them completely public and accessible to everyone, including any code on any site.  # Authentication  Forms of authentication:   - API Key 
*
* The version of the OpenAPI document: 0.0.1
* Contact: support@example.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "Success.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

Success::Success()
{
    m_Code = 0;
    m_Message = "";
    
}

Success::~Success()
{
}

void Success::validate()
{
    // TODO: implement validation
}

void to_json(nlohmann::json& j, const Success& o)
{
    j = nlohmann::json();
    j["code"] = o.m_Code;
    j["message"] = o.m_Message;
}

void from_json(const nlohmann::json& j, Success& o)
{
    j.at("code").get_to(o.m_Code);
    j.at("message").get_to(o.m_Message);
}

int32_t Success::getCode() const
{
    return m_Code;
}
void Success::setCode(int32_t const value)
{
    m_Code = value;
}
std::string Success::getMessage() const
{
    return m_Message;
}
void Success::setMessage(std::string const& value)
{
    m_Message = value;
}

}
}
}
}

